.TH YED-LANG-SYNTAX-Lua 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/lua \- Syntax highlighting for the Lua filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, lua, Lua
